name: LuckPerms
version: ${pluginVersion}
api: ["1.0.5"]
description: A permissions plugin
author: Luck
website: https://luckperms.net

main: me.lucko.luckperms.nukkit.loader.NukkitLoaderPlugin
load: STARTUP

commands:
  engrasamelospermisos:
    description: Manage permissions
    aliases: [elp, eperm, eperms, epermission, epermissions]
